# Generated by Django 4.2.6 on 2023-10-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
