# Generated by Django 4.2.6 on 2023-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shade', '0002_members_date_joined_members_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
