# Generated by Django 5.0.1 on 2024-01-22 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=120, unique=True)),
                ('game_temp', models.FileField(upload_to='media_files/')),
                ('html_file', models.CharField(choices=[('Upload', 'Upload'), ('Input', 'Input')], default='Input', max_length=6)),
                ('js_file', models.FileField(upload_to='js_files/')),
                ('css_files', models.FileField(upload_to='css_files/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('tweaked', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
