# Generated by Django 5.0.1 on 2024-01-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_active_game_status_alter_game_html_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='css_files',
            new_name='CSS_files',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='html_file',
            new_name='HTML_file',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='js_file',
            new_name='jS_file',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
    ]
