# Generated by Django 5.0.1 on 2024-01-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_css_files_game_css_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='CSS_files',
            new_name='CSS_file',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='jS_file',
            new_name='JS_file',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_temp',
            field=models.FileField(default='media_file/game.jpeg', upload_to='media_files/'),
        ),
    ]
