# Generated by Django 5.0.1 on 2024-01-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_css_files_game_css_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_temp',
            new_name='Image_View',
        ),
    ]
