# Generated by Django 5.0.1 on 2024-02-04 22:22

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_supports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Image_View',
            field=models.FileField(default='media_file/default/game.png', upload_to='media_files/', validators=[games.models.validate_image_view]),
        ),
    ]
