# Generated by Django 5.0.1 on 2024-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_image_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='Enjoy the game 😁', max_length=300),
        ),
    ]
