# Generated by Django 5.0.1 on 2024-02-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='Enjoy the game 🎮', max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
