# Generated by Django 5.0.1 on 2024-02-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.CharField(max_length=120),
        ),
    ]
