# Generated by Django 5.0.1 on 2024-02-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='supports',
            field=models.CharField(choices=[('Mobile And Pc', 'Mobile And Pc'), ('Pc only', 'Pc Only'), ('Mobile only', 'Mobile Only')], default='Mobile And Pc', max_length=14),
        ),
    ]
