# Generated by Django 5.0.1 on 2024-02-13 17:59

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_game_supports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='JS_file',
            field=models.FileField(default='js_files/default/new.js', upload_to='js_files/', validators=[games.models.validate_js]),
        ),
    ]
