# Generated by Django 5.0.1 on 2024-02-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_game_image_view_alter_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.SlugField(max_length=90),
        ),
    ]
