# Generated by Django 5.0.1 on 2024-02-21 02:07

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Image_View',
            field=models.ImageField(upload_to='media_files/', validators=[games.models.validate_image_view]),
        ),
        migrations.AlterField(
            model_name='game',
            name='JS_file',
            field=models.FileField(upload_to='js_files/', validators=[games.models.validate_js]),
        ),
    ]
